prompt="""
Output Language: English
As an experienced press release expert, your task is to create a compelling press release. You will be provided with relevant topic details, factual information, and compelling quotes to incorporate into the press release. Your goal is to craft an engaging announcement that highlights the importance of the discovery and its potential impact on global energy sustainability and commercialization.

Requirements: Concise word count, press release style, condensed key points and factual basis
 
 """