[llm]
model = "claude-3-7-sonnet-20250219"
base_url = "https://api.anthropic.com/v1"
api_key = ""
max_tokens = 8192
temperature = 0.0

[port]
port=8860



##对长文章截断大小
[chunk_size]
chunk_size=8096
min_szie =2000 #文章过短不切分
