[llm]
model = "claude-sonnet-4-20250514"
base_url = "https://api.anthropic.com/v1"
api_key = 
max_tokens = 10240
temperature = 0.0

[port]
port=8890



##对长文章截断大小
[chunk_size]
chunk_size=10240
min_szie =2000 #文章过短不切分
